# Alle hier gesetzten Werte können über `$addon->getProperty($key)` abgefragt werden

package: nv_deepl # Pflichtfeld
version: '0.1-dev' # Pflichtfeld
author: novinet GmbH & Co KG
supportpage: https://novinet.de

    
    
# Abhängigkeiten
# Anforderungen ans System oder anderere AddOns, um dieses AddOn installieren oder update zu können
requires:
    redaxo: '^5.12' # benötigt mindestens REDAXO 5.5
    php:
        version: '>=7.1' # benötigt mindestens PHP 5.6


page:
    title: translate:title
    icon: novinet-icon-logo
    perm: admin
    subpages:
        settings: { title: translate:settings }
        translate: { title: translate:translate, hidden: true }